name: Local Python 3.8.16 Python Machine Learning tests with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
      	python -m venv github_actions_demo
	      source github_actions_demo/bin/activate
        make install

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test
        
    - name: Format
      run: |
        make format
